# Copyright (c) 2023 Dawid Kurek <dawikur@gmail.com>

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
pretty = true
show_column_numbers = true

strict = true
ignore_missing_imports = true

[tool.clang-format]
entry = "clang-format-12 -i"
